In [2]:
from qiskit .quantum_info import Statevector, Operator
from numpy import sqrt
import numpy as np

In [3]:
zero, one = Statevector.from_label('0'), Statevector.from_label('1')
zero.tensor(one).draw('latex')

<IPython.core.display.Latex object>

**Create any operator and exucte and visualize it on the statevector**

In [4]:
plus = Statevector.from_label('+')
i_state = Statevector([1/sqrt(2), 1j/sqrt(2)])
psi = plus.tensor(i_state)
psi.draw('latex')

<IPython.core.display.Latex object>

In [6]:
X  = Operator([[0,1],[1,0]])
I = Operator([[1,0],[0,1]])

X.tensor(I)

Operator([[0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
          [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j],
          [1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
          [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j]],
         input_dims=(2, 2), output_dims=(2, 2))


In [7]:
psi.evolve(I^X).draw('latex')

<IPython.core.display.Latex object>

In [9]:
CX = Operator(
    [[1,0,0,0],
     [0,1,0,0],
     [0,0,0,1],
     [0,0,1,0]]
)

psi.evolve(CX).draw('latex')

<IPython.core.display.Latex object>

In [12]:
W = Statevector([0,1,1,0,1,0,0,0] / sqrt(3))
W.draw('latex')

<IPython.core.display.Latex object>

In [13]:
result, new_sv  = W.measure([0])
print(f'Measured : {result}\nState after measurement : ')
new_sv.draw('latex')

Measured : 1
State after measurement : 


<IPython.core.display.Latex object>

In [14]:
state_0 = Statevector([1,0])
state_1 = Statevector([0, 1])

tensor_product = state_0.tensor(state_1)
print(tensor_product)

Statevector([0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
            dims=(2, 2))


In [15]:
X  = Operator([[0,1],[1,0]])
I = Operator([[1,0],[0,1]])

XI = X.tensor(I)
print(XI)

Operator([[0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
          [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j],
          [1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
          [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j]],
         input_dims=(2, 2), output_dims=(2, 2))


In [16]:
psi = Statevector([0.6, 0.8])

Z = Operator([[1,0],[0,-1]])

new_state = psi.evolve(Z)
print(new_state)

Statevector([ 0.6+0.j, -0.8+0.j],
            dims=(2,))


#### ***CSWAP Matrix***

In [18]:
I = np.eye(2)

SWAP = np.array([[1,0,0,0],
     [0,0,1,0],
     [0,1,0,0],
     [0,0,0,1]])

CSWAP = np.zeros((8,8))

for i in range(8):
    if i ==5: 
        CSWAP[i, 6] = 1
    elif i == 6:
        CSWAP[i, 5] = 1
    else:
        CSWAP[i, i] = 1

print('CSWAP Matrix : \n', CSWAP)

CSWAP Matrix : 
 [[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


#### **Toffoli Matrix** 

In [19]:
Toffoli = np.zeros((8,8))

for i in range(8):
    if i == 6:
        Toffoli[i, 7] = 1
    elif i == 7:
        Toffoli[i, 6] = 1
    else:
        Toffoli[i, i] = 1

print('Toffoli Matrix : \n', Toffoli)

Toffoli Matrix : 
 [[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0.]]
